# Generated by Django 4.2.1 on 2023-05-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0006_alter_user_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
