# Generated by Django 4.2.1 on 2023-05-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_user_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(default="default.jpg", upload_to="profile_images"),
        ),
    ]
