# Generated by Django 4.2 on 2023-04-27 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_userfollowing_userfollowing_unique_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_song', to='social.song')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.tag')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(through='social.Tags', to='social.tag'),
        ),
    ]
