# Generated by Django 4.2 on 2023-04-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0003_tags_song_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="song",
            options={"ordering": ["-modification_date"]},
        ),
        migrations.AlterField(
            model_name="song",
            name="modification_date",
            field=models.DateField(auto_now=True, db_index=True),
        ),
    ]
