# Generated by Django 4.2.1 on 2023-05-13 09:08

import apps.social.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0005_event"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-start_date"]},
        ),
        migrations.AddField(
            model_name="song",
            name="midi_file",
            field=models.FileField(
                null=True, upload_to=apps.social.models.midi_directory_path
            ),
        ),
    ]
