# Generated by Django 4.2.1 on 2023-05-13 14:24

import apps.social.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0007_group_membership_group_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="mp3_file",
            field=models.FileField(
                null=True, upload_to=apps.social.models.mp3_directory_path
            ),
        ),
    ]
