# Generated by Django 4.2.1 on 2023-05-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0008_song_mp3_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
