# Generated by Django 4.2.1 on 2023-05-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0009_song_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
